### ISSUE TITLE
[1.20.1] Crash with Physics mod

### ISSUE THREAD

**Issue by MrKashew** [Jusey1/Kobolds#3]
Removing this mod fixed the issue for me, seems the structure generates banner in an incompatible way
Here is the log / info
https://github.com/haubna/PhysicsMod/issues/672

**Comment by Jusey1** [comment]
It's probably incompatible because the data that the Physics mod isn't save into the structure because I don't use said mod and wouldn't use other people's mods when saving the structure. They should just add a "if (bannerPattern != null) check to avoid this issue as I can't really do anything it looks like to me to fix this.
