### ISSUE TITLE
crash on server

### ISSUE THREAD

**Issue by GnomTocha** [Jusey1/Kobolds#3]
[crash-2021-05-31_17.14.23-server.txt](https://github.com/Jusey1/Kobolds/files/6571845/crash-2021-05-31_17.14.23-server.txt)
[crash-2021-05-31_17.15.23-server.txt](https://github.com/Jusey1/Kobolds/files/6571846/crash-2021-05-31_17.15.23-server.txt)
[debug.log](https://github.com/Jusey1/Kobolds/files/6571847/debug.log)
[latest.log](https://github.com/Jusey1/Kobolds/files/6571848/latest.log)

Bad mobs helped to keep playing safely. Namely, the ban on the appearance of ordinary kobolds. I did not find any other problems.
forge 36.1.23

**Comment by Jusey1** [comment]
Test with just the Kobolds mod itself and if no crashes happen, then test it with each mod in your modpack individually. Base on what the crash logs is saying... It's saying that "IHasArm" is not being found, which is a vanilla class file (not a new one from my mod but my mod does uses it).

Essentially, my mod isn't able to find "IHasArm" and thus is crashing. Since that's a vanilla file, I am suspecting that another mod is changing it or it's location, which seems possible since I am seeing mentions of Mixins within the logs as well.

**Comment by GnomTocha** [comment]
OK.  In the next couple of days I will test and give an answer.

**Comment by Jusey1** [comment]
Ye'h, need to figure out what is causing the vanilla file to be missing.

**Comment by Jusey1** [comment]
GriefPrivention causes this while mob protection flag is active. This isn't on my end so gonna close.
